// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjIdjsbVR8nfLH4yzXNjMR6MIZ1QMeJP8',
    appId: '1:754542508461:web:5c828ad37c0740db1d8924',
    messagingSenderId: '754542508461',
    projectId: 'adoptme-apps',
    authDomain: 'adoptme-apps.firebaseapp.com',
    storageBucket: 'adoptme-apps.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6bRyb14w72vs84AwXlxU3ty8ZF8U1yo4',
    appId: '1:754542508461:android:81952f8e042e78d01d8924',
    messagingSenderId: '754542508461',
    projectId: 'adoptme-apps',
    storageBucket: 'adoptme-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCajDDbIoH7KNRD9L1Qmdw-EBwNZ-rwHlo',
    appId: '1:754542508461:ios:9dadd3106e855ecd1d8924',
    messagingSenderId: '754542508461',
    projectId: 'adoptme-apps',
    storageBucket: 'adoptme-apps.appspot.com',
    iosClientId:
        '754542508461-g1i2lde6vjq3at09uu72lhgccebovd98.apps.googleusercontent.com',
    iosBundleId: 'com.example.adoptme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCajDDbIoH7KNRD9L1Qmdw-EBwNZ-rwHlo',
    appId: '1:754542508461:ios:9dadd3106e855ecd1d8924',
    messagingSenderId: '754542508461',
    projectId: 'adoptme-apps',
    storageBucket: 'adoptme-apps.appspot.com',
    iosClientId:
        '754542508461-g1i2lde6vjq3at09uu72lhgccebovd98.apps.googleusercontent.com',
    iosBundleId: 'com.example.adoptme',
  );
}
