// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVK8uqsOKFV3HoeBUKwPtxGULiI3iEzjA',
    appId: '1:408092142415:web:d55aacc806115bfa95b33a',
    messagingSenderId: '408092142415',
    projectId: 'helloword-ce191',
    authDomain: 'helloword-ce191.firebaseapp.com',
    storageBucket: 'helloword-ce191.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbnSwdHSHWFm9XrrfrYCAhekXxZgMmtj4',
    appId: '1:408092142415:android:d7e8a50023dabf3595b33a',
    messagingSenderId: '408092142415',
    projectId: 'helloword-ce191',
    storageBucket: 'helloword-ce191.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFApd-F9Fio1UR1qJWQDKm6YAD2RUL_i8',
    appId: '1:408092142415:ios:c7df2f7e5197a2fe95b33a',
    messagingSenderId: '408092142415',
    projectId: 'helloword-ce191',
    storageBucket: 'helloword-ce191.appspot.com',
    iosClientId: '408092142415-9579d97ji39v1oib6gmtq9s9las9fcup.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFApd-F9Fio1UR1qJWQDKm6YAD2RUL_i8',
    appId: '1:408092142415:ios:c7df2f7e5197a2fe95b33a',
    messagingSenderId: '408092142415',
    projectId: 'helloword-ce191',
    storageBucket: 'helloword-ce191.appspot.com',
    iosClientId: '408092142415-9579d97ji39v1oib6gmtq9s9las9fcup.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectd',
  );
}
